#
# Copyright 2016, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(D61_BSD)
#

all:
	doxygen

gui:
	doxywizard Doxyfile

clean:
	rm -rf html

help:
	@echo 'make all - Make RefOS docs.'
	@echo 'make gui - Start doxygen GUI interface and open doxygen config file.'
	@echo 'make clean - Clean all RefOS docs.'
	@echo 'make help - Display this help message.'
