# Copyright 2016, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

all:
	doxygen

gui:
	doxywizard Doxyfile

clean:
	rm -rf html

help:
	@echo 'make all - Make RefOS docs.'
	@echo 'make gui - Start doxygen GUI interface and open doxygen config file.'
	@echo 'make clean - Clean all RefOS docs.'
	@echo 'make help - Display this help message.'
