#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

all:
	doxygen

gui:
	doxywizard Doxyfile

clean:
	rm -rf html

help:
	@echo 'make all - Make RefOS docs.'
	@echo 'make gui - Start doxygen GUI interface and open doxygen config file.'
	@echo 'make clean - Clean all RefOS docs.'
	@echo 'make help - Display this help message.'
