# Copyright 2016, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

// DO NOT EDIT MANUALLY!!!\n
// This file was generated by CIDL - Simple C IDL Compiler.\n\n

{{for include in includes}}
    {{include}}\n
{{endfor}}
\n\n

int rpc_sv_{{ifname}}_dispatcher(void *rpc_userptr, uint32_t label) {\n
____switch (label) {\n

        {{for func_output in func_list}}
            {{func_output}}\n
        {{endfor}}

________default:\n
____________return -1;\n
____}\n
____return 0;\n
}
\n
