#
# Copyright 2016, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

apps-$(CONFIG_APP_FILE_SERVER)  += file_server

file_server: libmuslc libsel4 libelf librefossys librefos libcpio libdatastruct
