#
# Copyright 2016, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

apps-$(CONFIG_APP_NETHACK)  += nethack

nethack: libmuslc libsel4 librefossys librefos libdatastruct
