#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_PROCESS_SERVER)  += process_server

process_server-y                    = common libsel4 libmuslc libsel4allocman libsel4vka \
                                      libsel4platsupport libsel4muslcsys libsel4utils \
                                      libcpio libelf librefos libdatastruct libsel4simple \
                                      libsel4vspace libsel4utils libutils libsel4vspace
                                      
# Set up correct simple lib for our kernel
ifdef CONFIG_KERNEL_STABLE
process_server-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
process_server-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

process_server: kernel_elf $(process_server-y)
