#
# Copyright 2016, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

apps-$(CONFIG_APP_PROCESS_SERVER)  += process_server

process_server-y                    = common libsel4 libmuslc libsel4allocman libsel4vka \
                                      libsel4platsupport libsel4muslcsys libsel4utils \
                                      libcpio libelf librefos libdatastruct libsel4simple \
                                      libsel4vspace libsel4utils libutils libsel4vspace

process_server-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default

process_server: kernel_elf $(process_server-y)
