#
# Copyright 2016, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(D61_BSD)
#

apps-$(CONFIG_APP_PROCESS_SERVER)  += process_server

process_server-y                    = common libsel4 libmuslc libsel4allocman libsel4vka \
                                      libsel4platsupport libsel4muslcsys libsel4utils \
                                      libcpio libelf librefos libdatastruct libsel4simple \
                                      libsel4vspace libsel4utils libutils libsel4vspace

process_server-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default

process_server: kernel_elf $(process_server-y)
